
  [[customizations.user]]
  name = "cyrene"
  description = "Cyrene"
  groups = ["wheel"]
  password = "cyrene"

  [customizations.timezone]
  timezone = "Asia/Shanghai"

  [customizations.locale]
  languages = ["zh_CN.UTF-8"]
  keyboard = "us"
