# Declare /var dirs created by RPM %install scriptlets during the container
# build. bootc container lint requires all /var content to be listed here
# so systemd-tmpfiles recreates them correctly on first boot of a fresh
# deployment (where /var starts empty).
#
# Format: Type Path Mode User Group Age
d /var/lib/blueman                0755 root    root    -
d /var/lib/dnf                    0755 root    root    -
d /var/lib/geoclue                0755 geoclue geoclue -
d /var/cache/PackageKit           0755 root    root    -
d /var/cache/ibus                 0755 root    root    -
d /var/cache/ibus/bus             0755 root    root    -
d /var/cache/libX11               0755 root    root    -
d /var/cache/libX11/compose       0755 root    root    - 

